// Disposable native-app acceptance. Never pass a personal workspace/profile here.
import { startDaemon } from '../../dist/daemon/server.js';
import { ConnectorMcpClient } from '../../dist/mcp/client.js';
import { mkdtempSync, writeFileSync, readFileSync, chmodSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { createServer, request as httpsRequest } from 'node:https';
import { request as httpRequest } from 'node:http';
if(process.env.MODELBOT_NATIVE_ACCEPTANCE!=='1')throw new Error('Set MODELBOT_NATIVE_ACCEPTANCE=1 for a disposable fixture.');
const root=mkdtempSync(join(tmpdir(),'modelbot-native-tls-'));chmodSync(root,0o700);
const key=root+'/key.pem',cert=root+'/cert.pem';
const generated=spawnSync('openssl',['req','-x509','-newkey','rsa:2048','-nodes','-keyout',key,'-out',cert,'-days','1','-subj','/CN=localhost','-addext','subjectAltName=DNS:localhost'],{stdio:'ignore'});if(generated.status!==0)throw new Error('Test certificate generation failed');chmodSync(key,0o600);
const origin='https://localhost:7792',target='http://127.0.0.1:7791',token=randomUUID(),name='native-'+randomUUID().slice(0,8);
const proxy=createServer({key:readFileSync(key),cert:readFileSync(cert)},(req,res)=>{const up=httpRequest(target+req.url,{method:req.method,headers:{...req.headers,connection:'close'},agent:false},r=>{res.writeHead(r.statusCode,r.headers);r.pipe(res)});up.on('error',()=>{res.writeHead(502);res.end()});req.pipe(up)});
proxy.on('upgrade',(req,socket,head)=>{const up=httpRequest(target+req.url,{headers:req.headers});up.on('upgrade',(res,peer,first)=>{socket.write('HTTP/1.1 101 Switching Protocols\r\n'+Object.entries(res.headers).map(([k,v])=>k+': '+v).join('\r\n')+'\r\n\r\n');if(first.length)socket.write(first);if(head.length)peer.write(head);socket.pipe(peer).pipe(socket);peer.on('error',()=>socket.destroy());socket.on('error',()=>peer.destroy())});up.on('response',res=>{socket.end('HTTP/1.1 '+res.statusCode+' Rejected\r\nConnection: close\r\n\r\n');res.resume()});up.on('error',()=>socket.destroy());up.end()});
await new Promise(r=>proxy.listen(7792,'127.0.0.1',r));
const daemon=await startDaemon({port:7791,publicOrigin:origin,sqlitePath:root+'/state.sqlite',workspaceRoot:root+'/computers',bootstrapToken:token,mcpToken:token,idlePauseMin:0,declaredOrigins:{readable:['http://127.0.0.1:8080'],writable:['http://127.0.0.1:8080']},agentLoop:{model:'synthetic-native-acceptance',adapter:{kind:'openai_compat',complete:async()=>({tool_calls:[{id:'finish',name:'done',arguments:{summary:'Synthetic native result: launch is scheduled, not yet completed. END-NATIVE-RESULT',status:'success'}}],usage:{tokens_in:0,tokens_out:0,usd_est:0}})}}});
const call=(path,method='GET',body,headers={})=>new Promise((resolve,reject)=>{const req=httpsRequest(origin+path,{family:4,ca:readFileSync(cert),method,headers:{Origin:origin,'Content-Type':'application/json',...headers}},res=>{let value='';res.on('data',x=>value+=x);res.on('end',()=>{if(res.statusCode>=300){reject(new Error(path+':'+res.statusCode));return}resolve({headers:res.headers,body:value?JSON.parse(value):{}})})});req.on('error',reject);req.end(body===undefined?undefined:JSON.stringify(body))});
const boot=await call('/api/v1/session/bootstrap','POST',{token,label:'Native fixture owner'});const headers={Cookie:boot.headers['set-cookie'][0].split(';')[0],'X-CSRF-Token':boot.body.csrf};
await call('/api/v1/computers','POST',{name,capabilities:['browser'],persistent:false},headers);
const html='<meta charset="utf-8"><style>body{font:28px sans-serif;padding:32px}input{font:28px sans-serif;width:90%;padding:14px}</style><h1>Native control fixture</h1><label>Operator text<input autofocus oninput="fetch(\'/value\',{method:\'POST\',body:this.value})"></label>';
const server=`let value='';require('node:http').createServer((req,res)=>{if(req.url==='/value'){if(req.method==='POST'){let body='';req.on('data',d=>body+=d);req.on('end',()=>{value=body;res.end('ok')})}else res.end(value);return}res.setHeader('Content-Type','text/html;charset=utf-8');res.end(${JSON.stringify(html)})}).listen(8080,'127.0.0.1')`;
if(spawnSync('docker',['exec','-d','modelbot-'+name+'-browser','node','-e',server]).status!==0)throw new Error('Browser fixture failed');
const mcp=await ConnectorMcpClient.connectHttp({url:target+'/mcp',headers:{Authorization:'Bearer '+token}});const result=await mcp.callTool('browser_navigate',{url:'http://127.0.0.1:8080',wait_until:'domcontentloaded'});if(!JSON.parse(result.content[0].text).ok)throw new Error('Fixture navigation failed');await mcp.close();
writeFileSync(root+'/fixture.json',JSON.stringify({root,origin,target,name,headers,mcpToken:token,cert}),{mode:0o600});
console.log('Synthetic native HTTPS fixture: '+root+'/fixture.json');
process.on('SIGTERM',async()=>{try{const tasks=await call('/api/v1/tasks','GET',undefined,headers);for(const t of tasks.body.tasks)if(['running','paused'].includes(t.status))await call('/api/v1/tasks/'+t.id+'/cancel','POST',{},headers);await call('/api/v1/computers/'+name,'DELETE',undefined,headers);}finally{await daemon.close();proxy.close();process.exit()}});
